core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('customer/', include('customer.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/inventory/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'inventory'
urlpatterns = [
    path('new', views.NewInventory, name='new'),
    path('singles', views.SinglesInventory, name='singles'),
]

core/inventory/models.py
from typing_extensions import Required
from django.db import models
from django.contrib.auth.models import User

# Need to find a way to tie this to the TcgOrder table.
# Think the best option maybe to relate the SkuIds together
class SinglesInventory(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='singles_inventory')
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    purchase_price = models.FloatField()
    sell_price = models.FloatField()
    listed_on_tcg = models.CharField(max_length=255, null=True)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now=True)

class NewInventory(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='new_inventory')
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    purchase_price = models.FloatField()
    sell_price = models.FloatField()
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now=True)

core/inventory/forms.py
from django import forms
from .models import *


class SinglesForm(forms.ModelForm):
    id = forms.CharField(widget = forms.HiddenInput, required=False)
    name = forms.CharField(required=True)
    description = forms.CharField(required=True, max_length=255)
    purchase_price = forms.FloatField(required=True)
    sell_price = forms.FloatField(required=True)
    listed_on_tcg = forms.CharField(max_length=255, required=False)
    quantity = forms.IntegerField(required=True)

    class Meta:
        model = SinglesInventory
        exclude = ("user", )

class NewForm(forms.ModelForm):
    id = forms.CharField(widget = forms.HiddenInput, required=False)
    name = forms.CharField(required=True)
    description = forms.CharField(required=True, max_length=255)
    purchase_price = forms.FloatField(required=True)
    sell_price = forms.FloatField(required=True)
    quantity = forms.IntegerField(required=True)

    class Meta:
        model = NewInventory
        exclude = ("user", )

core/inventory/views.py
from wsgiref.util import request_uri
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from .models import NewInventory as NewInventoryModel
from .models import SinglesInventory as SinglesInventoryModel
from django.views.decorators.http import require_http_methods
from .forms import *


# Create your views here.
@require_http_methods(["GET", "POST"])
def NewInventory(request):
    if request.user.is_authenticated:
        if request.POST.get('delete'):
            item = NewInventoryModel.objects.get(id=request.POST.get('id'))
            item.delete()
        elif request.method == "POST":
            try:
                instance = NewInventoryModel.objects.get(id=request.POST.get('id'))
            except NewInventoryModel.DoesNotExist:
                instance = None
            except ValueError:
                instance = None
            form = NewForm(request.POST, instance=instance)
            if form.is_valid():
                item = form.save(commit=False)
                item.user = request.user
                item.save()
                return redirect("inventory:new")
        form = NewForm()
        new_inventory = request.user.new_inventory.all().order_by('-date_added')
        template = loader.get_template('inventory/new_inventory.html')
        context = {
            'new_inventory': new_inventory,
            'form': form,
        }
        return HttpResponse(template.render(context, request))
    return redirect("/")

@require_http_methods(["GET", "POST"])
def SinglesInventory(request):
    if request.user.is_authenticated:
        if request.POST.get('delete'):
            item = SinglesInventoryModel.objects.get(id=request.POST.get('id'))
            item.delete()

        elif request.method == "POST":
            try:
                instance = SinglesInventoryModel.objects.get(id=request.POST.get('id'))
            except SinglesInventoryModel.DoesNotExist:
                instance = None
            except ValueError:
                instance = None
            form = SinglesForm(request.POST, instance=instance)
            if form.is_valid():
                item = form.save(commit=False)
                item.user = request.user
                item.save()
                return redirect("inventory:singles")
        form = SinglesForm()
        singles_inventory = request.user.singles_inventory.all().order_by('-date_added')
        template = loader.get_template('inventory/singles_inventory.html')
        context = {
            'singles_inventory': singles_inventory,
            'form': form,
        }
        return HttpResponse(template.render(context, request))
    return redirect("/")

core/inventory/templates/inventory/new_inventory.html
{% extends "core/base.html" %}
{% block scripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
{% endblock scripts %}
{% block content %}
<div class="container table-responsive">
    <h3>New Inventory</h3>
    <table id="newTable" class="table table-fluid" aria-describedby="New Inventory Table">
        <thead>
            <tr>
                <th class="th-sm">Name</th>
                <th class="th-sm">Description</th>
                <th class="th-sm">Purchase Price</th>
                <th class="th-sm">Sell Price</th>
                <th class="th-sm">Quantity</th>
            </tr>
        </thead>
        {% for item in new_inventory %}
        <tr class="custom-clickable-row" id="{{ item.id }}">
            <td id="{{ item.id }}_name">{{ item.name }}</td>
            <td id="{{ item.id }}_description">{{ item.description }}</td>
            <td id="{{ item.id }}_purchase_price">{{ item.purchase_price }}</td>
            <td id="{{ item.id }}_sell_price">{{ item.sell_price }}</td>
            <td id="{{ item.id }}_quantity">{{ item.quantity }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Inventory</h4>
                <button class="close" type="button" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="popup">
                    <form method="post" class="form-container">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary mb-2" type="submit">Submit</button>
                        <button class="btn btn-primary mb-2" type="submit" name="delete" value="delete">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block footer %}
<script>
    $(document).ready(function () {
        $('#newTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    text: 'Add Item',
                    attr: {
                        'type': 'button',
                        'data-toggle': 'modal',
                        'data-target': '#myModal',
                        'tabindex': '-1',
                        'id': 'addItem',
                    }
                },
                'copy', 'csv', 'print'
            ]
        });
    });
    $(document).on('click', '.custom-clickable-row', function (e) {
        $('#id_name').val('');
        $('#id_description').val('');
        $('#id_purchase_price').val('');
        $('#id_sell_price').val('');
        $('#id_quantity').val('');
        let row_id = $(this).attr("id");
        $('#id_id').val(row_id);
        document.getElementById("addItem").click();
        $(this).find('td').each(function () {
            if ($(this).attr('id') === row_id + "_name") {
                $('#id_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_description") {
                $('#id_description').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_purchase_price") {
                $('#id_purchase_price').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_sell_price") {
                $('#id_sell_price').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_quantity") {
                $('#id_quantity').val($(this).text());
            }
        })
    });
</script>
{% endblock footer %}

core/inventory/templates/inventory/singles_inventory.html
{% extends "core/base.html" %}
{% block scripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
{% endblock scripts %}
{% block content %}
<div class="container table-responsive">
    <h3>Singles Inventory</h3>
    <table id="singleTable" class="table table-fluid" aria-describedby="Singles Inventory Table">
        <thead>
            <tr>
                <th class="th-sm">Name</th>
                <th class="th-sm">Description</th>
                <th class="th-sm">Purchase Price</th>
                <th class="th-sm">Sell Price</th>
                <th class="th-sm">Listed on TCG</th>
                <th class="th-sm">Quantity</th>
            </tr>
        </thead>
        {% for item in singles_inventory %}
        <tr class="custom-clickable-row" id="{{ item.id }}">
            <td id="{{ item.id }}_name">{{ item.name }}</td>
            <td id="{{ item.id }}_description">{{ item.description }}</td>
            <td id="{{ item.id }}_purchase_price">{{ item.purchase_price }}</td>
            <td id="{{ item.id }}_sell_price">{{ item.sell_price }}</td>
            <td id="{{ item.id }}_listed_on_tcg">{{ item.listed_on_tcg }}</td>
            <td id="{{ item.id }}_quantity">{{ item.quantity }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add New Inventory</h4>
                <button class="close" type="button" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="popup">
                    <form method="post" class="form-container">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary mb-2" type="submit">Submit</button>
                        <button class="btn btn-primary mb-2" type="submit" name="delete" value="delete">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block footer %}
<script>
    $(document).ready(function () {
        $('#singleTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
            {
                text: 'Add Item',
                attr: {
                    'type': 'button',
                    'data-toggle': 'modal',
                    'data-target': '#myModal',
                    'tabindex': '-1',
                    'id': 'addItem',
                }
            },
                'copy', 'csv', 'print'
            ]
        });
    });
    $(document).on('click', '.custom-clickable-row', function (e) {
        $('#id_name').val('');
        $('#id_description').val('');
        $('#id_purchase_price').val('');
        $('#id_sell_price').val('');
        $('#id_listed_on_tcg').val('');
        $('#id_quantity').val('');
        let row_id = $(this).attr("id");
        $('#id_id').val(row_id);
        document.getElementById("addItem").click();
        $(this).find('td').each(function () {
            if ($(this).attr('id') === row_id + "_name") {
                $('#id_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_description") {
                $('#id_description').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_purchase_price") {
                $('#id_purchase_price').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_sell_price") {
                $('#id_sell_price').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_listed_on_tcg") {
                $('#id_listed_on_tcg').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_quantity") {
                $('#id_quantity').val($(this).text());
            }
        })
    });
</script>
{% endblock footer %}