core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
    path('customer/', include('customer.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/customer/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'customer'
urlpatterns = [
    path('preorders', views.PreOrders, name='preorders'),
    path('store_credit', views.StoreCredit, name='store_credit'),
]

core/customer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class PreOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='pre_orders')
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=15)
    item = models.CharField(max_length=255)
    amount_paid = models.FloatField()
    item_picked_up = models.CharField(max_length=10)
    added_by = models.CharField(max_length=50)
    date_added = models.DateField(auto_now=True)

class StoreCredit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='store_credit')
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(max_length=50)
    phone_number = models.CharField(max_length=15)
    amount = models.FloatField()
    added_by = models.CharField(max_length=50)
    date_added = models.DateField(auto_now=True)

core/customer/forms.py
from django import forms
from .models import *


class PreOrderForm(forms.ModelForm):
    id = forms.CharField(widget = forms.HiddenInput, required=False)
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=50)
    phone_number = forms.CharField(max_length=15)
    item = forms.CharField(max_length=255)
    amount_paid = forms.FloatField()
    item_picked_up = forms.CharField(required=True)
    added_by = forms.CharField(max_length=50)

    class Meta:
        model = PreOrder
        exclude = ("user", )

class StoreCreditForm(forms.ModelForm):
    id = forms.CharField(widget = forms.HiddenInput, required=False)
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=50)
    phone_number = forms.CharField(max_length=15)
    amount = forms.FloatField()
    added_by = forms.CharField(max_length=50)

    class Meta:
        model = StoreCredit
        exclude = ("user", )

core/customer/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from .forms import PreOrderForm, StoreCreditForm
from .models import StoreCredit as StoreCreditModel
from .models import PreOrder as PreOrderModel

@require_http_methods(["GET", "POST"])
def StoreCredit(request):
    if request.user.is_authenticated:
        if request.POST.get('delete'):
            item = StoreCreditModel.objects.get(id=request.POST.get('id'))
            item.delete()
        
        elif request.method == "POST":
            try:
                instance = StoreCreditModel.objects.get(id=request.POST.get('id'))
            except StoreCreditModel.DoesNotExist:
                instance = None
            except ValueError:
                instance = None
            form = StoreCreditForm(request.POST, instance=instance)
            if form.is_valid():
                item = form.save(commit=False)
                item.user = request.user
                item.save()
                return redirect("customer:store_credit")
        form = StoreCreditForm()
        credit = request.user.store_credit.all().order_by('-date_added')
        template = loader.get_template('customer/storecredit.html')
        context = {
            'store_credit': credit,
            'form': form,
        }
        return HttpResponse(template.render(context, request))
    return HttpResponse("Please login.")

@require_http_methods(["GET", "POST"])
def PreOrders(request):
    if request.user.is_authenticated:
        if request.POST.get('delete'): 
            item = PreOrderModel.objects.get(id=request.POST.get('id'))
            item.delete()
        elif request.method == "POST":
            try: 
                instance = PreOrderModel.objects.get(id=request.POST.get('id'))
            except PreOrderModel.DoesNotExist:
                instance = None
            except ValueError:
                instance = None
            form = PreOrderForm(request.POST, instance=instance)
            if form.is_valid():
                item = form.save(commit=False)
                item.user = request.user
                item.save()
                return redirect("customer:preorders")
        form = PreOrderForm()
        preorders = request.user.pre_orders.all().order_by('-date_added')
        template = loader.get_template('customer/preorders.html')
        context = {
            'preorders': preorders,
            'form': form,
        }
        return HttpResponse(template.render(context, request))
    return HttpResponse("Please login.")
    

core/customer/templates/customer/preorders.html
{% extends "core/base.html" %}
{% load static %}
{% block scripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
<script src="{% static 'js/custom.js' %}"></script>
{% endblock scripts %}
{% block content %}
<div class="container table-responsive">
    <h3>PreOrders</h3>
    <table id="preorderTable" class="table table-fluid" aria-describedby="PreOrders Table">
        <thead>
            <tr>
                <th class="th-sm">First Name</th>
                <th class="th-sm">Last Name</th>
                <th class="th-sm">Email</th>
                <th class="th-sm">Phone Number</th>
                <th class="th-sm">Item</th>
                <th class="th-sm">Amount Paid</th>
                <th class="th-sm">Picked Up</th>
                <th class="th-sm">Added By</th>
            </tr>
        </thead>
        {% for item in preorders %}
        <tr class="custom-clickable-row" id="{{ item.id }}">
            <td id="{{ item.id }}_first_name">{{ item.first_name }}</td>
            <td id="{{ item.id }}_last_name"> {{ item.last_name }}</td>
            <td id="{{ item.id }}_email">{{ item.email }}</td>
            <td id="{{ item.id }}_phone_number">{{ item.phone_number }}</td>
            <td id="{{ item.id }}_item">{{ item.item }}</td>
            <td id="{{ item.id }}_amount_paid">{{ item.amount_paid }}</td>
            <td id="{{ item.id }}_item_picked_up">{{ item.item_picked_up }}</td>
            <td id="{{ item.id }}_added_by">{{ item.added_by }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add PreOrder</h4>
                <button class="close" type="button" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="popup">
                    <form method="post" class="form-container">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary mb-2" type="submit">Submit</button>
                        <button class="btn btn-primary mb-2" type="submit" name="delete" value="delete">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block footer %}
<script>
    $(document).ready(function () {
        $('#preorderTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    text: 'Add Item',
                    attr: {
                        'type': 'button',
                        'data-toggle': 'modal',
                        'data-target': '#myModal',
                        'tabindex': '-1',
                        'id': 'addItem',
                    }
                },
                'copy', 'csv', 'print'
            ],
        });
    });
    $(document).on('click', '.custom-clickable-row', function (e) {
        $('#id_first_name').val('');
        $('#id_last_name').val('');
        $('#id_email').val('');
        $('#id_phone_number').val('');
        $('#id_item').val('');
        $('#id_amount_paid').val('');
        $('#id_item_picked_up').val('');
        $('#id_added_by').val('');
        $('#id_id').val('');
        let row_id = $(this).attr("id");
        $('#id_id').val(row_id);
        document.getElementById("addItem").click();
        $(this).find('td').each(function () {
            if ($(this).attr('id') === row_id + "_first_name") {
                $('#id_first_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_last_name") {
                $('#id_last_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_email") {
                $('#id_email').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_phone_number") {
                $('#id_phone_number').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_item") {
                $('#id_item').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_amount_paid") {
                $('#id_amount_paid').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_item_picked_up") {
                $('#id_item_picked_up').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_added_by") {
                $('#id_added_by').val($(this).text());
            }
        })
    });
</script>
{% endblock footer %}

core/customer/templates/customer/storecredit.html
{% extends "core/base.html" %}
{% block scripts %}
<script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
{% endblock scripts %}
{% block content %}
<div class="container table-responsive">
    <h3>Store Credits</h3>
    <table id="creditTable" class="table table-fluid" aria-describedby="Store Credit Table">
        <thead>
            <tr>
                <th class="th-sm">First Name</th>
                <th class="th-sm">Last Name</th>
                <th class="th-sm">Email</th>
                <th class="th-sm">Phone Number</th>
                <th class="th-sm">Amount</th>
                <th class="th-sm">Added By</th>
            </tr>
        </thead>
        {% for item in store_credit %}
        <tr class="custom-clickable-row" id="{{ item.id }}">
            <td id="{{ item.id }}_first_name">{{ item.first_name }}</td>
            <td id="{{ item.id }}_last_name">{{ item.last_name }}</td>
            <td id="{{ item.id }}_email">{{ item.email }}</td>
            <td id="{{ item.id }}_phone_number">{{ item.phone_number }}</td>
            <td id="{{ item.id }}_amount">{{ item.amount }}</td>
            <td id="{{ item.id }}_added_by">{{ item.added_by }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Store Credit</h4>
                <button class="close" type="button" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="popup">
                    <form method="post" class="form-container" id="form">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary mb-2" type="submit">Submit</button>
                        <button class="btn btn-primary mb-2" type="submit" name="delete" value="delete">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block footer %}
<script>
    $(document).ready(function () {
        $('#creditTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    text: 'Add Item',
                    attr: {
                        'type': 'button',
                        'data-toggle': 'modal',
                        'data-target': '#myModal',
                        'tabindex': '-1',
                        'id': 'addItem',
                    }
                },
                'copy', 'csv', 'print'
            ]
        });
    });
    $(document).on('click', '.custom-clickable-row', function (e) {
        $('#id_first_name').val('');
        $('#id_last_name').val('');
        $('#id_email').val('');
        $('#id_phone_number').val('');
        $('#id_amount').val('');
        $('#id_added_by').val('');
        $('#id_id').val('');
        let row_id = $(this).attr("id");
        $('#id_id').val(row_id);
        document.getElementById("addItem").click();
        $(this).find('td').each(function () {
            if ($(this).attr('id') === row_id + "_first_name") {
                $('#id_first_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_last_name") {
                $('#id_last_name').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_email") {
                $('#id_email').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_phone_number") {
                $('#id_phone_number').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_amount") {
                $('#id_amount').val($(this).text());
            } else if ($(this).attr('id') === row_id + "_added_by") {
                $('#id_added_by').val($(this).text());
            }
        })
    });
</script>
{% endblock footer %}